apiVersion: v1
kind: Service
metadata:
  name: blue-green
  labels:
    app: blue-green
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http

  # Note here that we match both the app and the version
  selector:
    app: blue-green
    version: v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-v1
  labels:
    app: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green
      version: v1.0.0
  template:
    metadata:
      labels:
        app: blue-green
        version: v1.0.0
    spec:
      containers:
      - name: blue-green
        image: pritamrgb/k8s-image
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5
