apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-v2
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary
      version: v2.0.0
  template:
    metadata:
      labels:
        app: canary
        version: v2.0.0
    spec:
      containers:
      - name: canary
        image: pritamrgb/k8s-image
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v2.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 52
