apiVersion: v1
kind: Service
metadata:
  name: canary
  labels:
    app: canary
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: canary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-v1
  labels:
    app: canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: canary
      version: v1.0.0
  template:
    metadata:
      labels:
        app: canary
        version: v1.0.0
    spec:
      containers:
      - name: canary
        image: pritamrgb/k8s-image
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5
