apiVersion: apps/v1
kind: Deployment
metadata:
  name: pritam-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: webserver
        image: nginx:1.16.1
